global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'kubernetes-nodes'
    kubernetes_sd_configs:
      - role: node
        kubeconfig_file: "/home/ubuntu/.kube/config"

  - job_name: 'kubernetes-pods'
    kubernetes_sd_configs:
      - role: pod
        kubeconfig_file: "/home/ubuntu/.kube/config"

  - job_name: 'kubelet'
    scheme: https
    tls_config:
      insecure_skip_verify: true
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    kubernetes_sd_configs:
      - role: node
        kubeconfig_file: "/home/ubuntu/.kube/config"
    metrics_path: /metrics
    relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)

